### ISSUE TITLE
Support v2 KV secret engine

### ISSUE THREAD

**Issue by optiz0r** [morningconsult/docker-credential-vault-login#15]
#### Feature Description

The KV version 2 secret engine in recent versions of vault structures the paths slightly differently. A secret is read from `${mountpoint}/data/${path}` rather than `${mountpoint}/${path}`. And the resulting response has the expected `username` and `password` keys nested under a top-level `data` key.

#### Use Case(s)

The version 2 KV engine handles versioned secrets, allowing rollback to previous state.

**Comment by dbellinghoven** [comment]
@sarkis addressed this issue in https://github.com/morningconsult/docker-credential-vault-login/pull/23. Closing.
